// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/SuperMa/project/react/aitao_user_front/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/SuperMa/project/react/aitao_user_front/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('/Users/SuperMa/project/react/aitao_user_front/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('aitao_user_front', appParameters);
});